'''
graph_sigma_likelihoods.py
4/19/2025
Harry Lynch
Standalone test file to visualize the distributions generated by stdev_likelihood_gen.
Used this in order to validate that the distributions recieved passed the eye test and 
for some tuning later on. 
'''

from pathlib import Path
from data_io import load_sigma_likelihood
from globals import BIN_WIDTH_SIGMA

import numpy as np
import matplotlib.pyplot as plt

# Grab the likelihood
sigma_file = "../data/stdev_likelihood.txt"
like_sig, sig_min = load_sigma_likelihood(Path(sigma_file))

# Report num of bins
n_bins = like_sig.shape[1]
print ("Number of bins: ", n_bins)
# Configure the graph and display
sig_axis = sig_min + np.arange(n_bins) * BIN_WIDTH_SIGMA
plt.figure(figsize=(8, 4))
plt.plot(sig_axis, like_sig[0], label="Birds")
plt.plot(sig_axis, like_sig[1], label="Airplanes")
plt.xlabel("Rolling stdev(v) bin center [m/s]")
plt.ylabel("P(stdev-bin | class)")
plt.title("Likelihood curves for rolling speed standard deviation")
plt.legend()
plt.tight_layout()
plt.show()
